[package]
name = "guarana"
version = "0.1.0"
edition = "2021"

[lib]
name = "guarana"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36"
hd-wallet = {version = "0.6.1", features = ["curve-ed25519", "edwards"]}
generic-ec = { version = "0.4", default-features = false }
